name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Get Yarn cache directory
        id: yarn_cache_dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn_cache_dir.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: ESLint cache
        uses: actions/cache@v2
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.yml') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.yml') }}-
            ${{ runner.os }}-eslint-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check
        run: yarn run check

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint --cache

      - name: Check formatting
        run: yarn run check-fmt
